language: node_js
node_js:
- '11'
cache:
  yarn: true
  directories:
  - node_modules
install:
- yarn
script:
- yarn test
before_deploy:
- yarn build
deploy:
  provider: npm
  email: onoueorigami@gmail.com
  skip_cleanup: true
  api_key:
    secure: fWM+SaGPpf6Xt7mg2N5p9010a1YI+wJAGo/kTpdv7YJ+H3scICR5uWkZQ0Jgcx7hFSFXKMzvBAx6qArUBp4wNZDIKNKldoww3ebDuVIvUCBIPnvfmL91CbyOnHLwQbzgfPp3zGdYd/n0/2eDgcOn7IOX24yrdwVNjVmZR2t7Vm2yMxMawsifs+UUZDEi9URMKtPFOphJAufIlsFpHLuS+mzTd2FPIjv2+WTri9BtGwLQCQhf81ZjBv9hsKkffTp+A94j1K9YcH015DqHgUffSDplS5V4BUGt1B5bWAiPLYR4fHLv96nBu+J76Y6dFD4HXfVXxZ6Xi86fOrJVuuTDvKI4FEkZTv7jh2Fyi9xvl6nri27myqqAhQHgVgaruW8j0t7EDifGjiCEyDtBA3vE2BCAZnB+cWy+GXlyZjHs5ICt/gCIUGs58RuDNqQEBGSVjV87ud5qecDU2CZMIfaOaD50Kii4rUqYvrAIaBD5WzrubI4NCcZW1iAtClcU86FD8OVCNnGOgepmjB5Mnyj4TXy6TmZPxWXnnEY9+OK3gClYCvnMgMWhrI+np6BEgt9JuIInnYplbVNT96imHPbLfqHjI7SsBEhRtsGb1tLKtGMdaJ47nXPYL9J2HaaaYYep+kZs+jsIYN9do85KpqwGtG4YBVN4F/TPDTDilPueVPk=
  on:
    tags: true
